customCommands:
  - key: "<C-R>"
    context: "global"
    prompts:
      - type: "input"
        title: "Enter topics, or press [Enter] to upload all"
        key: "RevupTopics"
        initialValue: ""
    command: "revup upload {{.Form.RevupTopics}}"
    subprocess: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  nerdFontsVersion: "3"

os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} --server /tmp/nvim-server.pipe --remote-tab {{filename}}"
